/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.6.0
 *
 * Project: 'ethernet.debug+HE' 
 * Target:  'debug+HE' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* AlifSemiconductor::RTOS&AzureRTOS:Kernel:Core@6.2.1 */
// enabling global pre include
        #define TX_SINGLE_MODE_SECURE
/* AlifSemiconductor::RTOS&AzureRTOS:Netx Duo:Core@6.1.7 */
// enabling global pre include
        #define NX_PACKET_ALIGNMENT  8
 #define NX_DHCP_CLIENT_USER_CREATE_PACKET_POOL


#endif /* PRE_INCLUDE_GLOBAL_H */
